### ISSUE TITLE
gpu绑定问题

### ISSUE THREAD

**Issue by banbsyip** [YCG09/chinese_ocr#124]
2018-11-20 08:58:47.913787: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-11-20 08:58:47.913818: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-20 08:58:47.913823: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-11-20 08:58:47.913828: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-11-20 08:58:47.913934: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4042 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-11-20 08:58:57.618243: E tensorflow/stream_executor/cuda/cuda_dnn.cc:455] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2018-11-20 08:58:57.618275: F tensorflow/core/kernels/conv_ops.cc:713] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms) 
运行的时候出现了GPU没有绑定的问题

**Comment by YCG09** [comment]
看看这个能有帮助不，https://github.com/tensorflow/tensorflow/issues/6698

**Comment by banbsyip** [comment]
> 看看这个能有帮助不，[tensorflow/tensorflow#6698](https://github.com/tensorflow/tensorflow/issues/6698)

我看过了，他们主要是版本不匹配问题，我看了下我的配置Ubuntu16.0.4，tensorflow-gpu1.8.0，cuda9，CUDNN7.看问题贴出来的配置表单，我的配置没有问题。下面两行是运行时新出现的错误提示。
2018-11-20 09:53:09.157482: E tensorflow/stream_executor/cuda/cuda_dnn.cc:455] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2018-11-20 09:53:09.157516: F tensorflow/core/kernels/conv_ops.cc:713] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms)

**Comment by banbsyip** [comment]
2018-11-20 09:52:45.603365: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-11-20 09:52:45.761758: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-11-20 09:52:45.762981: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.72GiB
2018-11-20 09:52:45.763025: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-11-20 09:52:46.288215: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-20 09:52:46.288241: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-11-20 09:52:46.288246: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-11-20 09:52:46.288412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4042 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-11-20 09:52:46.289047: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 3.95G (4238737408 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY

**Comment by YCG09** [comment]
我是在tf1.3环境下开发的，没有试过1.8的兼容性

**Comment by banbsyip** [comment]
> 我是在tf1.3环境下开发的，没有试过1.8的兼容性

整了一天，只要python中 import TensorFlow，就会出现ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory问题,在pycharm里也不能运行，后来重装了一下TensorFlow1.10.0的在python下也还是那个问题，找到那个文件夹，下面的文件竟然是 libcusolver.so.9.0，但是在pycharm里可以运行了，运行了一下你和那张讲金融的图片，GPU下跑是12秒，1080Ti 4g的显卡，我看了下你这个项目的以往问题，发现竟然和人家CPU的一个速度，感觉很不明白为什么

**Comment by banbsyip** [comment]
> tf1.3

能提供一下你实验的硬件环境和软件环境吗？我这的环境是1080Ti 4g显卡，TensorFlow1.8.0，cuda9 cuDnn7，NVIDIA415.13，非常感谢！

**Comment by YCG09** [comment]
TitanX 12g，TensorFlow1.3.0，cuda8，cudnn5，NVIDIA384.90

**Comment by banbsyip** [comment]
> TitanX 12g，TensorFlow1.3.0，cuda8，cudnn5，NVIDIA384.90

谢谢，问下你这个配置跑哪个样例图片要多长时间？

**Comment by YCG09** [comment]
第一次启动比较慢，需要加载模型，后面就快了，检测+识别平均一张图1s左右

**Comment by banbsyip** [comment]
> 第一次启动比较慢，需要加载模型，后面就快了，检测+识别平均一张图1s左右

我目前想做个纯数字识别训练，请问下，训练的时间大概要多长时间？

**Comment by fire717** [comment]
> > 第一次启动比较慢，需要加载模型，后面就快了，检测+识别平均一张图1s左右
> 
> 我目前想做个纯数字识别训练，请问下，训练的时间大概要多长时间？

看数据量大小 有多少个batch    你那个配置训练估计半天多点吧

**Comment by banbsyip** [comment]
>           只是速度很慢。要9秒才能识别例子中的图片。为什么这么慢呢？tf1.8
有时候会很慢的，
1，可能你是头一次运行需要加载模型
2，GPU内存不足，运行时间过慢（内存不足时多半会报错，这个可能性较小）
3，没有用GPU，只用了CPU。

**Comment by Qsongl** [comment]
你好，请问你解决了这个问题了吗。我现在是训练一轮100多个小时，然后看了一下，并没有用到gpu训练，自己也没有改过其他的代码，请问您知道怎么解决吗 @banbsyip

**Comment by banbsyip** [comment]
> 你好，请问你解决了这个问题了吗。我现在是训练一轮100多个小时，然后看了一下，并没有用到gpu训练，自己也没有改过其他的代码，请问您知道怎么解决吗 @banbsyip

在他的项目里有一个setup.sh，进到里面把for cpu注释掉，GitHub里有说明，指定GPU可以百度进行了，在ctpn/text_detect.py文件里可以添加指定gpu代码

**Comment by banbsyip** [comment]
> > 你好，请问你解决了这个问题了吗。我现在是训练一轮100多个小时，然后看了一下，并没有用到gpu训练，自己也没有改过其他的代码，请问您知道怎么解决吗 @banbsyip
> 
> 在他的项目里有一个setup.sh，进到里面把for cpu注释掉，GitHub里有说明，指定GPU可以百度进行了，在ctpn/text_detect.py文件里可以添加指定gpu代码

sh setup.sh

**Comment by banbsyip** [comment]
> > > 你好，请问你解决了这个问题了吗。我现在是训练一轮100多个小时，然后看了一下，并没有用到gpu训练，自己也没有改过其他的代码，请问您知道怎么解决吗 @banbsyip
> > 
> > 
> > 在他的项目里有一个setup.sh，进到里面把for cpu注释掉，GitHub里有说明，指定GPU可以百度进行了，在ctpn/text_detect.py文件里可以添加指定gpu代码
> 
> sh setup.sh

要下载tnesorflow-gpu版本的，如果是tensorflow的话不能绑定gpu

**Comment by simplify23** [comment]
> > 看看这个能有帮助不，[tensorflow/tensorflow#6698](https://github.com/tensorflow/tensorflow/issues/6698)
> 
> 我看过了，他们主要是版本不匹配问题，我看了下我的配置Ubuntu16.0.4，tensorflow-gpu1.8.0，cuda9，CUDNN7.看问题贴出来的配置表单，我的配置没有问题。下面两行是运行时新出现的错误提示。
> 2018-11-20 09:53:09.157482: E tensorflow/stream_executor/cuda/cuda_dnn.cc:455] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2018-11-20 09:53:09.157516: F tensorflow/core/kernels/conv_ops.cc:713] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo(), &algorithms)

你好,请问这个问题你后来时怎么解决的,tf版本改了也不对
