### ISSUE TITLE
请问大家，显卡是GTX1050的，训练DenseNet + CTC可以，训练CTPN就报内存溢出，怎么解决

### ISSUE THREAD

**Issue by Hannibal7ecter** [YCG09/chinese_ocr#136]
显卡是GTX1050的，训练DenseNet + CTC可以，训练CTPN就如下
报内存溢出

2018-12-11 14:30:30.490045: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 819.56MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
iter: 0 / 50000, total loss: 1.3369, model loss: 0.6587, rpn_loss_cls: 0.6587, rpn_loss_box: 0.0000, lr: 0.000010
speed: 74.525s / iter
2018-12-11 14:30:46.725168: W tensorflow/core/common_runtime/bfc_allocator.cc:275] Allocator (GPU_0_bfc) ran out of memory trying to allocate 137.21MiB.  Current allocation summary follows.
2018-12-11 14:30:46.725213: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (256):   Total Chunks: 115, Chunks in use: 115. 28.8KiB allocated for chunks. 28.8KiB in use in bin. 4.0KiB client-requested in use in bin.
2018-12-11 14:30:46.725222: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (512):   Total Chunks: 12, Chunks in use: 12. 6.0KiB allocated for chunks. 6.0KiB in use in bin. 6.0KiB client-requested in use in bin.

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,64,562,1000] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: gradients/conv1_2/Conv2D_grad/Conv2DBackpropInput = Conv2DBackpropInput[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/conv1_2/Conv2D_grad/ShapeN, conv1_2/weights/read, gradients/conv1_2/conv1_2_grad/ReluGrad)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: Adam/update/_136 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2351_Adam/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
我也修改了如下几个地方
yml文件
IS_MULTISCALE: False
NET_NAME: VGGnet
ANCHOR_SCALES: [16]
NCLASSES: 2
USE_GPU_NMS: True
TRAIN:
  restore: 0
  max_steps: 50000
  SOLVER: Adam
  OHEM: False
  RPN_BATCHSIZE: 1
  BATCH_SIZE: 1
  LOG_IMAGE_ITERS: 100
  DISPLAY: 10
  SNAPSHOT_ITERS: 1000
  HAS_RPN: True
  LEARNING_RATE: 0.00001
  MOMENTUM: 0.9
  GAMMA: 0.1
  STEPSIZE: 30000 # 每迭代STEPSIZE次，LEARNING_RATE *= GAMMA
  IMS_PER_BATCH: 1
  BBOX_NORMALIZE_TARGETS_PRECOMPUTED: True
  RPN_POSITIVE_OVERLAP: 0.7
  PROPOSAL_METHOD: gt
  BG_THRESH_LO: 0.0
  PRECLUDE_HARD_SAMPLES: True
  BBOX_INSIDE_WEIGHTS: [0, 1, 0, 1]
  RPN_BBOX_INSIDE_WEIGHTS: [0, 1, 0, 1]
  RPN_POSITIVE_WEIGHT: -1.0
  FG_FRACTION: 0.3
  WEIGHT_DECAY: 0.0005
TEST:
  HAS_RPN: True
  DETECT_MODE: H  # O
还是运行不起来，求帮助

**Comment by JacobShenHdu** [comment]
您好，我使用mx150显卡2G显存同样out of memory，请问你解决了吗？

**Comment by Qsongl** [comment]
请问您训练DenseNet + CTC修改代码了吗，我的怎么出现了这个问题呢
![image](https://user-images.githubusercontent.com/41495766/50071884-3d22cf80-020e-11e9-955f-54c4573c13b7.png)

**Comment by YCG09** [comment]
@Qsongl py2还是py3

**Comment by Qsongl** [comment]
@YCG09 解决了，感谢

**Comment by WangXuanBT** [comment]
应该是显存不够大导致的，把batch_size改小一下应该就好了

**Comment by ql106** [comment]
> @Qonglpy2还是py3

我在训练densenet+ctc 出现这个错误怎么解决

**Comment by whjdhu** [comment]
调小图片的尺寸（512,512,3）
